version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    restart: always
    ports:
    - 8080:80
    volumes:
    - ./src/html/:/var/www/html/:ro
  worker-indexer:
    build:
      context: .
      dockerfile: Dockerfile-cli
    restart: always
    environment:
    - WAIT_WHEN_DONE=3600
    command: /app/app.php indexer
    volumes:
    - ./src/html/:/app/:ro
  worker-conv:
    build:
      context: .
      dockerfile: Dockerfile-cli
    restart: always
    environment:
    - WAIT_WHEN_DONE=3600
    command: /app/app.php conv
    volumes:
    - ./src/html/:/app/:ro 