FROM php:8-cli

LABEL org.opencontainers.image.authors="Andreas Kasper <andreas.kasper.github@goo1.de>"

WORKDIR /app/
ENTRYPOINT ["/app/app.php"]
CMD ["app.php"]

RUN apt-get update -y \
    && mkdir /in \
    && mkdir /out \
    && mkdir /data \
    && apt-get install -y git ffmpeg zlib1g-dev libzip-dev libjpeg-dev libpng-dev libwebp-dev imagemagick \
    && sed -i 's/policy domain="coder" rights="none" pattern="PDF"/policy domain="coder" rights="read | write" pattern="PDF"/g' /etc/ImageMagick-6/policy.xml \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
    

RUN docker-php-ext-configure gd --with-webp --with-jpeg \
    && docker-php-ext-install pdo_mysql mysqli bcmath gd zip sockets

VOLUME /in
VOLUME /out
VOLUME /data

ADD /src/html /app/

RUN chmod 0777 /app/app.php

#RUN apt-get update \
#    && apt-get install php-xdebug \
#    && apt-get clean