name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'
#weekly
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: andreaskasper
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: /.
          file: Dockerfile-web
          push: true
          tags: andreaskasper/avflow:web
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: /.
          file: Dockerfile-cli
          push: true
          tags: andreaskasper/avflow:cli
